### ISSUE TITLE
unauthenticated packages

### ISSUE THREAD

**Issue by keyurshah** [weareinteractive/ansible-php5-newrelic#4]
Hello,

I'm trying to install in Ubuntu 16 LTS and encountering this error during install.

WARNING: The following packages cannot be authenticated!
  newrelic-php5-common newrelic-daemon newrelic-php5

I can modify to allow unathenticated packages, but wanted to know if that is a concern.

Also, for PHP 7, should we specify the /etc/php/7.0/mods-available directory for the newrelic.ini?

Thanks.

**Comment by franklinkim** [comment]
Hi, haven't installed it in that env yet but warnings like these usually come because:

> apt-key is used to manage the list of keys used by apt to verify packages. Packages which have been verified using these keys will be considered trusted. To update the local keyring with the keyring of Ubuntu archive keys and removes from the keyring the archive keys which are no longer valid.
```
$ sudo apt-key update
$ sudo apt-get update
```

But this seems to be a [known error](https://discuss.newrelic.com/t/new-relic-gpg-key-is-no-longer-trusted-on-ubuntu-16-04-lts/36696/14) which seems to have been resolved!? 
If you can reproduce it, you might want to contribute to the forum...


I think you would need to specify the new location, yes.

**Comment by keyurshah** [comment]
ok, thank you very much. I'll try with a clean system and see what it reports and then post back to that thread. 

thanks for all your ansible roles by the way. it's saved me quite a bit of time!

**Comment by franklinkim** [comment]
Cool! Let me know if it runs through so I can update the systems list.

Pleasure, nice to hear that someone's using them :)
